import type { Database } from "bun:sqlite";
import { list } from "./store.ts";
import type { EventType, KnowledgeEvent, NewKnowledgeEvent } from "./types.ts";
import { append } from "./store.ts";
import { foldConstitution } from "./fold.ts";

// §5.2 trust story — "your data, always ejectable."
//
// Users can dump the entire event log to JSONL for backup or migration,
// restore it into a fresh DB idempotently (content_hash dedupe), and
// emit an AGENTS.md projection to meet the community-standard file
// AI coding tools have converged on (§5.4).

export interface ExportOptions {
  workspaceId?: string;
  projectId?: string;
  /** If true, include superseded events. Default false — export only the active set. */
  includeSuperseded?: boolean;
}

export function exportEventsToJsonl(db: Database, opts: ExportOptions = {}): string {
  const events = list(db, {
    workspaceId: opts.workspaceId,
    projectId: opts.projectId,
    activeOnly: !opts.includeSuperseded,
  });
  return events.map((e) => JSON.stringify(e)).join("\n") + (events.length ? "\n" : "");
}

export function importEventsFromJsonl(db: Database, jsonl: string): { inserted: number; skipped: number } {
  let inserted = 0;
  let skipped = 0;
  for (const raw of jsonl.split("\n")) {
    const line = raw.trim();
    if (!line) continue;
    let parsed: KnowledgeEvent;
    try {
      parsed = JSON.parse(line) as KnowledgeEvent;
    } catch {
      // Malformed lines: fail-soft — the export/import round trip must
      // tolerate hand-edits.
      skipped++;
      continue;
    }
    // Minimum required semantic payload — malformed rows are skipped rather
    // than raising, because export/import must survive hand-edits and
    // partial dumps.
    if (!parsed?.type || !parsed?.scope || !parsed?.subject) { skipped++; continue; }
    const asNew: NewKnowledgeEvent = {
      id: parsed.id,
      workspaceId: parsed.workspaceId ?? "local",
      projectId: parsed.projectId ?? "local",
      actorKind: parsed.actorKind,
      actorId: parsed.actorId,
      actorName: parsed.actorName,
      taskId: parsed.taskId ?? null,
      executionId: parsed.executionId ?? null,
      type: parsed.type,
      scope: parsed.scope,
      subject: parsed.subject,
      body: parsed.body ?? "",
      paths: parsed.paths ?? [],
      confidence: parsed.confidence,
      validFrom: parsed.validFrom,
      supersedes: parsed.supersedes ?? null,
    };
    try {
      const res = append(db, asNew);
      if (res.inserted) inserted++;
      else skipped++;
    } catch {
      skipped++;
    }
  }
  return { inserted, skipped };
}

// §5.4 — projection to AGENTS.md. Not a fold from scratch (that's
// constitution.md) — this file targets the community standard shape:
// bullet list of team conventions and gotchas that any AI coding tool
// (Cursor, Copilot, Codex, Cline) reads. Rulings/gotchas only; the
// per-task and per-execution stuff has no place here.

export function projectAgentsMd(db: Database, opts: ExportOptions = {}): string {
  const decisions = list(db, {
    workspaceId: opts.workspaceId, projectId: opts.projectId, type: "decision" as EventType, activeOnly: true,
  });
  const conventions = list(db, {
    workspaceId: opts.workspaceId, projectId: opts.projectId, type: "convention" as EventType, activeOnly: true,
  });
  const gotchas = list(db, {
    workspaceId: opts.workspaceId, projectId: opts.projectId, type: "gotcha" as EventType, activeOnly: true,
  });

  const lines: string[] = [];
  lines.push("# AGENTS.md");
  lines.push("");
  lines.push("Team-wide guidance for AI coding assistants working in this repo.");
  lines.push("Generated by `agent-trail knowledge export` — do not hand-edit;");
  lines.push("instead add a ruling with `agent-trail context add` or answer a");
  lines.push("decision ticket, then re-export.");
  lines.push("");

  section(lines, "Conventions", conventions.reverse());
  section(lines, "Decisions", decisions.reverse());
  section(lines, "Gotchas", gotchas.reverse());

  return lines.join("\n").trim() + "\n";
}

function section(out: string[], title: string, events: KnowledgeEvent[]): void {
  if (events.length === 0) return;
  out.push(`## ${title}`);
  out.push("");
  for (const ev of events) {
    const date = ev.validFrom.slice(0, 10);
    out.push(`- **${date} · ${ev.actorName}** — ${ev.subject}`);
    if (ev.body.trim().length) {
      const indented = ev.body.trim().split("\n").map((l) => `  ${l}`).join("\n");
      out.push(indented);
    }
  }
  out.push("");
}

// Regenerated markdown — a full constitution rendered from the log, useful
// for `git diff`ing what the pack contains without opening the DB.
export function projectConstitutionMd(db: Database, opts: ExportOptions = {}): string {
  return foldConstitution(db, { workspaceId: opts.workspaceId, projectId: opts.projectId }).markdown + "\n";
}
