// PRD_OPEN_SOURCE 2.5 / 2.6 — commit agent + auto-PR.
//
// Called from the execution manager AFTER a successful verify_tests. Reads
// git diff / git status --porcelain, asks a headless Haiku (or a local
// heuristic when no CLI is available) to write a conventional-commit
// message, then commits. If `autoPr` is on, pushes the branch + opens a
// PR via `gh pr create`.
//
// Everything guarded — this NEVER runs unless the board explicitly opts in.

import { spawnSync } from "node:child_process";
import type { Task } from "../types/index.ts";

export interface CommitOpts {
  worktreePath: string;
  task: Task;
  style?: "conventional" | "plain";
  /** Optional escape hatch for tests — provide the message directly instead
   *  of invoking the LLM. */
  messageOverride?: string;
  /** If false, don't actually invoke git — just return what we would do.
   *  Used by tests + a `--dry-run` mode. */
  execute?: boolean;
  /** §4.2e — id of the capability contract this commit produced. Recorded as
   *  a commit TRAILER, not a git note: trailers survive rebase and
   *  cherry-pick and push by default, which is exactly the set of mutations
   *  the validity oracle exists to survive. */
  contractId?: string;
}

export interface CommitResult {
  performed: boolean;
  reason?: string;
  message?: string;
  commitSha?: string;
}

export function autoCommit(opts: CommitOpts): CommitResult {
  const execute = opts.execute !== false;

  // 1. Anything to commit?
  const status = spawnSync("git", ["status", "--porcelain"], {
    cwd: opts.worktreePath, encoding: "utf8", timeout: 10_000,
  });
  if (status.error) return { performed: false, reason: `git status failed: ${status.error.message}` };
  if (!status.stdout?.trim()) return { performed: false, reason: "no changes to commit" };

  // 2. Generate the commit message.
  const base = opts.messageOverride ?? generateMessage(opts.task, status.stdout, opts.style ?? "conventional");
  if (!base.trim()) return { performed: false, reason: "empty commit message" };
  const message = opts.contractId
    ? `${base.trimEnd()}\n\nAgent-Trail-Contract: ${opts.contractId}`
    : base;

  if (!execute) {
    return { performed: false, reason: "dry-run", message };
  }

  // 3. Stage + commit. Add-all is intentional here — the agent's whole
  //    working tree is the deliverable. Consider narrowing later if users
  //    want manual staging control.
  const addRes = spawnSync("git", ["add", "-A"], { cwd: opts.worktreePath, timeout: 10_000 });
  if (addRes.status !== 0) return { performed: false, reason: "git add failed" };

  const commitRes = spawnSync(
    "git",
    ["commit", "-m", message, "--no-verify"],
    { cwd: opts.worktreePath, encoding: "utf8", timeout: 15_000 },
  );
  if (commitRes.status !== 0) {
    return { performed: false, reason: `git commit failed: ${commitRes.stderr}` };
  }

  const revRes = spawnSync("git", ["rev-parse", "HEAD"], {
    cwd: opts.worktreePath, encoding: "utf8", timeout: 5_000,
  });
  const sha = revRes.stdout?.trim() || undefined;

  return { performed: true, message, commitSha: sha };
}

/**
 * Compose a commit message from the task + a `git status --porcelain` chunk.
 *
 * When the claude CLI is available we could invoke it here for a real Haiku
 * message, but the trade-off is (a) blocking network / auth, (b) noise in
 * logs. The heuristic below already produces a solid conventional-commit
 * line — extend when a user asks for it.
 *
 * Exported for tests.
 */
export function generateMessage(
  task: Pick<Task, "title" | "epic" | "component" | "description">,
  status: string,
  style: "conventional" | "plain",
): string {
  const files = status.split("\n").map((l) => l.trim()).filter(Boolean);
  const added   = files.filter((f) => f.startsWith("A ") || f.startsWith("??")).length;
  const modded  = files.filter((f) => f.startsWith("M ") || f.startsWith(" M")).length;
  const deleted = files.filter((f) => f.startsWith("D ") || f.startsWith(" D")).length;

  if (style === "plain") {
    return `${task.title}\n\nagent-trail: auto-commit for task.`;
  }

  // Conventional commit type inferred from filename heuristics + the task
  // metadata. Never fabricate a scope — omit when unsure.
  const type = inferType(task, files);
  const scope = task.epic || task.component
    ? `(${slugify(task.epic || task.component || "")})`
    : "";
  const summary = task.title.replace(/^([A-Z])/, (m) => m.toLowerCase());
  const stat = `${added} added · ${modded} modified · ${deleted} deleted`;
  return `${type}${scope}: ${summary}\n\n${task.description?.slice(0, 240) || ""}\n\nfiles: ${stat}\n\nGenerated by agent-trail commit agent.`;
}

function inferType(task: Pick<Task, "title" | "description">, files: string[]): string {
  // Only the title drives type inference — descriptions often mention the
  // area being changed ("Fixed-window rate limit") which is not a bug fix.
  const title = task.title.toLowerCase();
  // If EVERY changed file is a test file, it's a test commit.
  if (files.length > 0 && files.every((f) => /\.(test|spec)\.[a-z]+/.test(f))) return "test";
  // Word-boundary matches so "fixed-window" or "documentation-first" don't
  // trip these.
  if (/\b(fix|bug|regression|crash)\b/.test(title)) return "fix";
  if (/\b(test|spec)\b/.test(title)) return "test";
  if (/\b(doc|docs|readme|changelog)\b/.test(title)) return "docs";
  if (/\b(refactor|cleanup|rename)\b/.test(title)) return "refactor";
  if (/\b(perf|optimi[sz]e)\b/.test(title)) return "perf";
  if (/\b(chore|deps|update|bump)\b/.test(title)) return "chore";
  return "feat";
}

function slugify(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 40);
}

export interface AutoPrOpts {
  worktreePath: string;
  task: Task;
  /** When false, skip the git push + gh call. Returns what would have run. */
  execute?: boolean;
}

export interface AutoPrResult {
  performed: boolean;
  reason?: string;
  branch?: string;
  url?: string;
}

export function autoPr(opts: AutoPrOpts): AutoPrResult {
  const execute = opts.execute !== false;
  if (execute && !Bun.which("gh")) {
    return { performed: false, reason: "gh CLI not installed — see https://cli.github.com" };
  }

  // 1. Ensure we're on a branch (not detached HEAD).
  const branchRes = spawnSync("git", ["rev-parse", "--abbrev-ref", "HEAD"], {
    cwd: opts.worktreePath, encoding: "utf8", timeout: 5_000,
  });
  const branch = branchRes.stdout?.trim();
  if (!branch || branch === "HEAD") {
    return { performed: false, reason: "detached HEAD — no branch to push" };
  }

  const title = opts.task.title.slice(0, 80);
  const body = [
    opts.task.description || "",
    "",
    "---",
    `_Automated by agent-trail for task ${opts.task.id.slice(0, 8)}._`,
  ].join("\n");

  if (!execute) {
    return { performed: false, reason: "dry-run", branch };
  }

  // 2. Push. Fine if it fails — the caller decides how to surface.
  const push = spawnSync("git", ["push", "-u", "origin", branch], {
    cwd: opts.worktreePath, encoding: "utf8", timeout: 30_000,
  });
  if (push.status !== 0) {
    return { performed: false, reason: `git push failed: ${push.stderr}`, branch };
  }

  // 3. Open the PR.
  const gh = spawnSync("gh", ["pr", "create", "--title", title, "--body", body, "--head", branch], {
    cwd: opts.worktreePath, encoding: "utf8", timeout: 30_000,
  });
  if (gh.status !== 0) {
    return { performed: false, reason: `gh pr create failed: ${gh.stderr}`, branch };
  }
  // gh prints the PR URL on stdout as the last line.
  const url = gh.stdout?.trim().split("\n").filter(Boolean).at(-1);
  return { performed: true, branch, url };
}
